#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

# Remove surface and features
rm -f constant/triSurface/motorBike.obj.gz
rm -f constant/triSurface/motorBike.eMesh
rm -rf constant/extendedFeatureEdgeMesh

#------------------------------------------------------------------------------
